name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Build Metadata-API
        run: |
          chmod +x ./gradlew
          ./gradlew distTar
          mkdir actions
          cp ./build/distributions/metadata-*.tar ./actions/metadata.tar
      - name: Build and push Docker images (latest)
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: metadata-api/metadata
          tag: latest
          dockerfile: Dockerfile
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}